name: AccountLock
main: net.cryptum.dev.accountLock.AccountLockMain
version: 0.3
description: Allows you to password protect your account within the server, added security
commands:
     alock:
        description: Account management functions 
        usage: |
           /<alock> [setPassword]|[lock]|[unlock]|[lockR]|[unlockR]|[resetPassword]
depend: [Vault]            
    